In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor,AdaBoostRegressor
from xgboost import XGBRegressor

In [2]:
df=pd.read_csv(r"C:\Users\yash0\Downloads\cardekho.csv")

In [3]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.50,1197.0,82.85,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.30,1248.0,73.9,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0

In [4]:
df.isna().sum()

name                    0
year                    0
selling_price           0
km_driven               0
fuel                    0
seller_type             0
transmission            0
owner                   0
mileage(km/ltr/kg)    221
engine                221
max_power             221
seats                 221
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(1202)

In [6]:
df.dtypes

name                   object
year                    int64
selling_price           int64
km_driven               int64
fuel                   object
seller_type            object
transmission           object
owner                  object
mileage(km/ltr/kg)    float64
engine                float64
max_power              object
seats                 float64
dtype: object

##### Data Cleaning:

In [7]:
from warnings import filterwarnings
filterwarnings('ignore')

In [8]:
df['max_power']=pd.to_numeric(df['max_power'],errors='coerce')

In [9]:
df.dtypes

name                   object
year                    int64
selling_price           int64
km_driven               int64
fuel                   object
seller_type            object
transmission           object
owner                  object
mileage(km/ltr/kg)    float64
engine                float64
max_power             float64
seats                 float64
dtype: object

In [10]:
df=df.dropna()

In [11]:
df.isna().sum()

name                  0
year                  0
selling_price         0
km_driven             0
fuel                  0
seller_type           0
transmission          0
owner                 0
mileage(km/ltr/kg)    0
engine                0
max_power             0
seats                 0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(1189)

In [13]:
df.drop_duplicates()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74.00,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78.00,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90.00,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.20,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8121,Maruti Wagon R VXI BS IV with ABS,2013,260000,50000,Petrol,Individual,Manual,Second Owner,18.90,998.0,67.10,5.0
8122,Hyundai i20 Magna 1.4 CRDi,2014,475000,80000,Diesel,Individual,Manual,Second Owner,22.54,1396.0,88.73,5.0
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.50,1197.0,82.85,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110.00,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.30,1248.0,73.90,5.0

##### Feature Engineering:

In [14]:
import datetime

In [15]:
current_year= datetime.datetime.now().year

In [16]:
df['car_age']= current_year- df['year']

##### Train Test Split:

In [17]:
from sklearn.model_selection import train_test_split

X=df.drop(['year','selling_price'],axis=1)
y=df['selling_price']

xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
X.isna().sum()

name                  0
km_driven             0
fuel                  0
seller_type           0
transmission          0
owner                 0
mileage(km/ltr/kg)    0
engine                0
max_power             0
seats                 0
car_age               0
dtype: int64

In [19]:
print(X.shape)
print(y.shape)

(7906, 11)
(7906,)

##### Data Preprocessing:

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [21]:
df.dtypes

name                   object
year                    int64
selling_price           int64
km_driven               int64
fuel                   object
seller_type            object
transmission           object
owner                  object
mileage(km/ltr/kg)    float64
engine                float64
max_power             float64
seats                 float64
car_age                 int64
dtype: object

In [22]:
num_features= xtrain.select_dtypes(include=['int64','float64']).columns.tolist()
categorical_features = xtrain.select_dtypes(include=['object', 'category']).columns.tolist()

preprocessor=ColumnTransformer(
    transformers=[('cat',OneHotEncoder(handle_unknown='ignore'),categorical_features)],
    remainder='passthrough'
)

##### Model Training:

In [23]:
# create object for each model:
lr=LinearRegression()
dtr=DecisionTreeRegressor()
gbr=GradientBoostingRegressor()
abr=AdaBoostRegressor()
xgbr=XGBRegressor()

In [27]:
# create dictionary, for value make a list of model name & model:
models = {'a':['LR',lr],
          'b':['DTR',dtr],
          'c':['GBR',gbr],
          'd':['ABR',abr],
          'e':['XGBR',xgbr]
         }

In [28]:
from sklearn.metrics import mean_absolute_error,r2_score,root_mean_squared_error
from sklearn.pipeline import make_pipeline

In [29]:
model_score=[]
for model in models:
    model_name=models[model][0]
    estimator=models[model][1]

    print('Training Model: ',model_name)

    # Encoding + Model training:
    pipe=make_pipeline(preprocessor,estimator)
    pipe.fit(xtrain,ytrain)

    #Predict:
    ypred=pipe.predict(xtest)

    #Evaluation:
    MAE= mean_absolute_error(ytest,ypred)
    R2= r2_score(ytest,ypred)
    RMSE= root_mean_squared_error(ytest,ypred)
    print('MAE:',MAE)
    print('R2_score:',R2)
    print('RMSE:',RMSE)
    model_score.append([model_name,R2,MAE,RMSE])

Training Model:  LR
MAE: 278984.7669810714
R2_score: 0.6988683849486941
RMSE: 457571.5298369729
Training Model:  DTR
MAE: 68316.07680151706
R2_score: 0.9750695164178845
RMSE: 131657.67135739213
Training Model:  GBR
MAE: 95272.0276022356
R2_score: 0.9686016693130047
RMSE: 147752.2481321941
Training Model:  ABR
MAE: 339285.37318680383
R2_score: 0.797839983998312
RMSE: 374911.23029651545
Training Model:  XGBR
MAE: 70858.2421875
R2_score: 0.9825823903083801
RMSE: 110046.2421875

In [30]:
model_score

[['LR', 0.6988683849486941, 278984.7669810714, 457571.5298369729],
 ['DTR', 0.9750695164178845, 68316.07680151706, 131657.67135739213],
 ['GBR', 0.9686016693130047, 95272.0276022356, 147752.2481321941],
 ['ABR', 0.797839983998312, 339285.37318680383, 374911.23029651545],
 ['XGBR', 0.9825823903083801, 70858.2421875, 110046.2421875]]

#### check whether XGBoost is overfitting:

In [33]:
# check whether XGBoost is overfitting:
train_pred=pipe.predict(xtrain)
test_pred=pipe.predict(xtest)

print('Train R2:',r2_score(ytrain,train_pred))
print('Test R2:',r2_score(ytest,test_pred))

print('Train MAE:',mean_absolute_error(ytrain,train_pred))
print('Test MAE:',mean_absolute_error(ytest,test_pred))

print('Train RMSE:',root_mean_squared_error(ytrain,train_pred))
print('Test RMSE:',root_mean_squared_error(ytest,test_pred))

Train R2: 0.9907921552658081
Test R2: 0.9825823903083801
Train MAE: 57511.3671875
Test MAE: 70858.2421875
Train RMSE: 77569.328125
Test RMSE: 110046.2421875

#### Tuning:

In [44]:
from sklearn.model_selection import GridSearchCV

xgb_pipeline= make_pipeline(
    preprocessor,
    XGBRegressor(random_state=42)
)

params={
    'xgbregressor__n_estimators': [100,200,300],
    'xgbregressor__max_depth': [3,5,7],
    'xgbregressor__learning_rate': [0.01,0.05,0.1]
}

grid= GridSearchCV(
    xgb_pipeline,
    param_grid=params,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1
)

grid.fit(xtrain,ytrain)

print('Best parameters:',grid.best_params_)
print('Best CV r2:',-grid.best_score_)

Best parameters: {'xgbregressor__learning_rate': 0.1, 'xgbregressor__max_depth': 7, 'xgbregressor__n_estimators': 300}
Best CV r2: 75154.48958333333

In [45]:
best_model=grid.best_estimator_
test_pred=best_model.predict(xtest)

print('Test R2:',r2_score(ytest,test_pred))
print('Test MAE:',mean_absolute_error(ytest,test_pred))
print('Test RMSE:',root_mean_squared_error(ytest,test_pred))

Test R2: 0.9850035905838013
Test MAE: 63926.00390625
Test RMSE: 102111.4609375

#### Check Overfitting for the tuned model:

In [46]:
# Check overfitting for the tuned model
train_pred = best_model.predict(xtrain)
test_pred = best_model.predict(xtest)

print("Train R2:", r2_score(ytrain, train_pred))
print("Test R2:", r2_score(ytest, test_pred))

print("Train MAE:", mean_absolute_error(ytrain, train_pred))
print("Test MAE:", mean_absolute_error(ytest, test_pred))

Train R2: 0.9930775165557861
Test R2: 0.9850035905838013
Train MAE: 50496.828125
Test MAE: 63926.00390625

#### Save & Load model:

In [48]:
# Save model:
import joblib
joblib.dump(best_model,"used_car_price_model.pkl")
print("Model saved successfully!")

Model saved successfully!

In [49]:
# Load model:
loaded_model=joblib.load('used_car_price_model.pkl')
print('Model loaded successfully')

Model loaded successfully

#### Verify that predictions still works

In [52]:
original_pred=best_model.predict(xtest)
loaded_pred=loaded_model.predict(xtest)

print('Predictions match:',(original_pred==loaded_pred).all())

Predictions match: True

#### Predict the price of a new car

In [54]:
print(xtrain.columns.tolist())

['name', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner', 'mileage(km/ltr/kg)', 'engine', 'max_power', 'seats', 'car_age']

In [56]:
new_car = pd.DataFrame([{
    'name': 'Maruti Swift Dzire VDI',
    'km_driven': 50000,
    'fuel': 'Diesel',
    'seller_type': 'Individual',
    'transmission': 'Manual',
    'owner': 'First Owner',
    'mileage(km/ltr/kg)': 23.0,
    'engine': 1248.0,
    'max_power': 74.0,
    'seats': 5.0,
    'car_age': 6
}])

predicted_price=loaded_model.predict(new_car)
print("Predicted selling price:", predicted_price[0])

Predicted selling price: 705868.6

#### Deploy:

In [57]:
import os
print(os.getcwd())
print(os.path.exists('used_car_price_model.pkl'))

C:\Users\yash0\ML
True

In [58]:
folder = os.path.join(os.path.expanduser("~"), "Desktop", "car_price_app")
os.makedirs(folder, exist_ok=True)

joblib.dump(best_model, os.path.join(folder, "used_car_price_model.pkl"))

print("Saved to:", folder)

Saved to: C:\Users\yash0\Desktop\car_price_app

In [59]:
import os

print("OneDrive path:", os.environ.get("OneDrive"))
print("Desktop path:", os.path.join(os.path.expanduser("~"), "Desktop"))

OneDrive path: C:\Users\yash0\OneDrive
Desktop path: C:\Users\yash0\Desktop

In [60]:
folder = os.path.join(
    os.environ["OneDrive"],
    "Desktop",
    "car_price_app"
)

os.makedirs(folder, exist_ok=True)

file_path = os.path.join(folder, "used_car_price_model.pkl")

joblib.dump(best_model, file_path)

print("File exists:", os.path.exists(file_path))
print("Saved location:", file_path)

File exists: True
Saved location: C:\Users\yash0\OneDrive\Desktop\car_price_app\used_car_price_model.pkl

In [61]:
%pip install streamlit pandas joblib scikit-learn xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: streamlit in c:\programdata\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: scikit-learn in c:\users\yash0\appdata\roaming\python\python313\site-packages (1.8.0)
Requirement already satisfied: xgboost in c:\users\yash0\appdata\roaming\python\python313\site-packages (3.3.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\programdata\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\programdata\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: scipy>=1.10.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.